travis:
  secure:
    BINSTAR_TOKEN: FQZNGhNR1vS98p63McNFJPhBwP/cS9nS63G4kBaoki9PMJmYNrry+PMW+o8TofKikwmv/jZUvi+Van8qMPyevNivUCq6I1R5UXtVShWVQVWaCSMdjuxKOqrfebu6AEOVoNVxmL2Xt92saSPmzmrwT7wmEsitH7RxwE5ymiyEm7RUH74ys8fIIyGF8gw2SmlJr8D63yd7/wRR8DzhswL2ojEdvlmB+H6+ONgmdQ5EwJG+XvoeJSrROckIKNmkiaN2LjrUwa51f0jjdIYrcWv7Mhj2kclFDTDXgkyFZS1HoUepFFSbLnbrBdXZm7pQH8CwfbhAXvMHG1bgv4HVTK6dOMTVaZuf7XvPiZsIE9HgnoQFEIztywYauD4VyTBw94WLWV+Nhexhqfr7MujdWUWlDr0N4xdigNRL1dGkcax6OImwW07zUhI3qphgxT95TvGUrgEQcQvxwcXyWn+XGufyQy9RKp17UMRfCRiU8KNmH6lq5f/WI2OcLyvIJlAaMtnZ42mURLd65ZDwhZy6JWfOduOAl9CtdwVDiHa+E/iBJMu/ameLTLDmv1feaoZyZwBVRxQsj4CKiVkZu1UJaI2j3fLMxzMI+wqfmxVnPXLCDm62yW/D6fKcdRsq4Pf/YXFHdsEfxNFaGw2RlFzepO0452ysJ0WtTXJSini/QXjgRa0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
