travis:
  secure:
    BINSTAR_TOKEN: IG9PuVEu3wPg6iMV7ZQJgcYqATgHhx0M7dnUzdDlhm5v2kCqEOLZkvWveCzAcsSChoqK6Tk0oyMMVqEtbgU3tVuK1wNbTd2lwdOu9R0pF1fUT1Jfut17eGZCWE1jgXiY2gDAmqzm+So8IEt5qN6WEJkPr+T0z0StxQmZ6n6OgPANRZsIIOfLtgg91RgwpEJQL/sWYFWmufvKQEXUHgol6A12s87KAit/TskqD6uPCRGjph2N3e3AXcX7ghj7XtpLJYvDrtI0t+Rr90V1O+qeAPa2k8IF6ay7bXNh5RUh32QvLyrWLMwiox7yooXx61/72+u89h7mFfe3e7dbJnRCUTvP48EKx5kmv1wg6SQt0nu48bZigkPP45/6rQ8SZSY0jXQpV1iQUk3bSYg9Y9c3MJLyg2oXKxfwGkmTNcZJaNz84aTnZHtfO3L42pVzpUDNiMt+ELpyLNY0vudRmDp8VG5RX+NR+23YtLRDgNZndA2WG+7mO6eGUotO0CXsHAOOr45Q5LBwa8Y2WM5nVmrqi4OjKt3TVIrdmcZjWc1U64rNzMTCmimaNp5q2lsMvmKgV3RRKOGQQqI1tYIFT+nsN8UL0Rw53xswWAE9dEWXbMMezyZYs1H2As1F2cc8lqSTIlaRtYEaWX2yZpksJoW0S1sNDiqtw4tVd5F5aNmm8TE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
